# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewfileDesc < Formula
  desc "brewfile-desc add descriptions of formulae to Brewfile."
  homepage "https://github.com/k1LoW/brewfile-desc"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/brewfile-desc/releases/download/v0.1.0/brewfile-desc_v0.1.0_darwin_arm64.zip"
      sha256 "b80ad9f758e52afdcab27c3eea56a6dbd30e19cae94c65d95c6503c1b7c16963"

      def install
        bin.install 'brewfile-desc'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/brewfile-desc/releases/download/v0.1.0/brewfile-desc_v0.1.0_darwin_amd64.zip"
      sha256 "65aaf0d5dfe3624698aa1feac61d834ec6cbaeb47ebdd062622e906dc5774738"

      def install
        bin.install 'brewfile-desc'
      end
    end
  end
end
