# This file was generated by GoReleaser. DO NOT EDIT.
class Connectedp < Formula
  desc "Check your MacBook power cable connection."
  homepage "https://github.com/k1LoW/connectedp"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/connectedp/releases/download/v0.1.0/connectedp_v0.1.0_darwin_amd64.zip"
    sha256 "309c988d19f7a79309507523a3eb7c4ebd7e0eaceb8831c24b71f41cf09ace6e"
  elsif OS.linux?
  end

  def install
    bin.install 'connectedp'
  end
end
