# This file was generated by GoReleaser. DO NOT EDIT.
class Connected < Formula
  desc "Check your MacBook power cable connection."
  homepage "https://github.com/k1LoW/connected"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/connected/releases/download/v0.3.0/connected_v0.3.0_darwin_amd64.zip"
    sha256 "ec0b8303844ba26be081c9f642d2cd16cbb11198672478fb9b7768fafdf6b717"
  elsif OS.linux?
  end

  def install
    system './connected', 'completion', 'bash', '--out', 'connected.bash'
    system './connected', 'completion', 'zsh', '--out', 'connected.zsh'
    bin.install 'connected'
    bash_completion.install 'connected.bash' => 'connected'
    zsh_completion.install 'connected.zsh' => '_connected'
  end
end
