# This file was generated by GoReleaser. DO NOT EDIT.
class Connected < Formula
  desc "Check your MacBook power cable connection."
  homepage "https://github.com/k1LoW/connected"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/connected/releases/download/v0.2.0/connected_v0.2.0_darwin_amd64.zip"
    sha256 "bb6212b8669523737ae6dca7886441659838a704ad6572d1f519c44d15340fc2"
  elsif OS.linux?
  end

  def install
    system './connected', 'completion', 'bash', '--out', 'connected.bash'
    system './connected', 'completion', 'zsh', '--out', 'connected.zsh'
    bin.install 'connected'
    bash_completion.install 'connected.bash' => 'connected'
    zsh_completion.install 'connected.zsh' => '_connected'
  end
end
