# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirmap < Formula
  desc "dirmap is a tool for generating a directory map."
  homepage "https://github.com/k1LoW/dirmap"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.3.3/dirmap_v0.3.3_darwin_amd64.zip"
      sha256 "9c43163c746fd2cd705d76edaa0795336e494c0077aebc7454a93deefed368cf"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.3.3/dirmap_v0.3.3_darwin_arm64.zip"
      sha256 "f2973aacf6c816a39b984ff8cbfdbf7d26ee423c8ebc7f4dde72feb659af71f7"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.3.3/dirmap_v0.3.3_linux_amd64.tar.gz"
      sha256 "1ca706d98e1e5d68d5b5d690fbd4344451360e0fba4c48a5eaf03ae49a38c8dd"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
  end
end
