# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirmap < Formula
  desc "dirmap is a tool for generating a directory map."
  homepage "https://github.com/k1LoW/dirmap"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.6.1/dirmap_v0.6.1_darwin_amd64.zip"
      sha256 "9e6ea504607f77294f5d48d3aa6d261e60982a3935d1ba65adf82efe9c6e9351"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.6.1/dirmap_v0.6.1_darwin_arm64.zip"
      sha256 "341a8b950780073e6632729a18d8fecaafaf3cfc27b1ff7eefbb49c2aba43369"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.6.1/dirmap_v0.6.1_linux_amd64.tar.gz"
      sha256 "8c42b448e10ed8614000dd6b50d82d73c6eacd9301375524cac1ec2c16710517"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
  end
end
