# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirmap < Formula
  desc "dirmap is a tool for generating a directory map."
  homepage "https://github.com/k1LoW/dirmap"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.3.0/dirmap_v0.3.0_darwin_amd64.zip"
      sha256 "a661ca820a9b67815d0a9a088544ad50b6af19c1d64eced29ad433fd28c56b1f"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.3.0/dirmap_v0.3.0_darwin_arm64.zip"
      sha256 "a7f1fd8513392a800eecad33a24de7c1a3499167c1f7c482ea1c84d17824e02b"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/dirmap/releases/download/v0.3.0/dirmap_v0.3.0_linux_amd64.tar.gz"
      sha256 "23485696c4ced40344aa4d785a74e3d26ce319ac7a44962625b2f981d447969a"

      def install
        bin.install 'dirmap'
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'bash')
        (bash_completion/'dirmap').write output
        output = Utils.safe_popen_read("#{bin}/dirmap", 'completion', 'zsh')
        (zsh_completion/'_dirmap').write output
      end
    end
  end
end
