# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ebk < Formula
  desc "ebk is a tiny tool for ebook."
  homepage "https://github.com/k1LoW/ebk"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/ebk/releases/download/v0.2.3/ebk_v0.2.3_darwin_arm64.zip"
      sha256 "b1c7787f63fe23ca3e4e46f55c44e3bc7eb465327d7d86f1cd4bd6d2c20e2e71"

      def install
        bin.install "ebk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ebk/releases/download/v0.2.3/ebk_v0.2.3_darwin_amd64.zip"
      sha256 "95b02139906c0b40cdf8080ad92fb24356f34f8420bfff587b7e4170a46ea40e"

      def install
        bin.install "ebk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ebk/releases/download/v0.2.3/ebk_v0.2.3_linux_amd64.tar.gz"
      sha256 "48bb3be447617ee6a167780d39caef6135f3180d0ce90363c28b8ed79e05ab9f"

      def install
        bin.install "ebk"
      end
    end
  end
end
