# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ebk < Formula
  desc "ebk is a tiny tool for ebook."
  homepage "https://github.com/k1LoW/ebk"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/ebk/releases/download/v0.2.5/ebk_v0.2.5_darwin_arm64.zip"
      sha256 "94e42aaaaa49d8294eb86dfe6de8511191d71f9a97e3c765cd75fb3dd9450000"

      def install
        bin.install "ebk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ebk/releases/download/v0.2.5/ebk_v0.2.5_darwin_amd64.zip"
      sha256 "f14b710779037db9355e214b3b2233e55eca6e986cf679479a478b10a734182b"

      def install
        bin.install "ebk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ebk/releases/download/v0.2.5/ebk_v0.2.5_linux_amd64.tar.gz"
      sha256 "2405f67cc09bad42d759d4c6aea860169adbd516736fc43d256219c93243e121"

      def install
        bin.install "ebk"
      end
    end
  end
end
