# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evry < Formula
  desc "evry split STDIN stream and execute specified command every N lines/seconds."
  homepage "https://github.com/k1LoW/evry"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/evry/releases/download/v0.3.0/evry_v0.3.0_darwin_arm64.zip"
      sha256 "54ba3b8331f50d96190b1469b1938ea399fb669ae8cfa4dc0710e4e85bed3b02"

      def install
        bin.install "evry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/evry/releases/download/v0.3.0/evry_v0.3.0_darwin_amd64.zip"
      sha256 "a5336c902c3fa7384075cda74f205c5c7b6643b5f086f4b5580c8c9917f7b3f4"

      def install
        bin.install "evry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k1LoW/evry/releases/download/v0.3.0/evry_v0.3.0_linux_arm64.tar.gz"
      sha256 "8cafa6d6b9c3b6c7309642d9577745600b550a1b9f517eb94626a651f87485ce"

      def install
        bin.install "evry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/evry/releases/download/v0.3.0/evry_v0.3.0_linux_amd64.tar.gz"
      sha256 "f786e345f6215e798bbce466eb5a27a2630f436ef3fd38a0774cffe72a9947ad"

      def install
        bin.install "evry"
      end
    end
  end
end
