# This file was generated by GoReleaser. DO NOT EDIT.
class Filt < Formula
  desc "filt is a interactive/realtime stream filter."
  homepage "https://github.com/k1LoW/filt"
  version "0.3.0"

  if OS.mac?
    url "https://github.com/k1LoW/filt/releases/download/v0.3.0/filt_v0.3.0_darwin_amd64.zip"
    sha256 "c9660f14f4bf93f9c6f8b14abdc32490af24a60e02077d982a2196dab8f70c41"
  elsif OS.linux?
    url "https://github.com/k1LoW/filt/releases/download/v0.3.0/filt_v0.3.0_linux_amd64.tar.gz"
    sha256 "d8de8abe066ac0c113a81e88885318fa76b1fe0c10136a06eed93838bf0e5652"
  end

  def install
    bin.install 'filt'
  end
end
