# This file was generated by GoReleaser. DO NOT EDIT.
class Frgm < Formula
  desc "frgm is a command snippets (fragments) manager."
  homepage "https://github.com/k1LoW/frgm"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/frgm/releases/download/v0.1.2/frgm_v0.1.2_darwin_amd64.zip"
    sha256 "b3ac22954eb7febeea463e4be9dc57c86a739e1ee4448b56a2d89d7c49dd00ae"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/frgm/releases/download/v0.1.2/frgm_v0.1.2_linux_amd64.tar.gz"
      sha256 "aab5fdbe6e86557604e0e447522de3a3d199174299b3d8f26121bf4d3b47539a"
    end
  end

  def install
    system './frgm', 'completion', 'bash', '--out', 'frgm.bash'
    system './frgm', 'completion', 'zsh', '--out', 'frgm.zsh'
    bin.install 'frgm'
    bash_completion.install 'frgm.bash' => 'frgm'
    zsh_completion.install 'frgm.zsh' => '_frgm'
  end
end
