# This file was generated by GoReleaser. DO NOT EDIT.
class Frgm < Formula
  desc "frgm is a meta snippet (fragment) manager."
  homepage "https://github.com/k1LoW/frgm"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/frgm/releases/download/v0.7.0/frgm_v0.7.0_darwin_amd64.zip"
    sha256 "8d5d20c64771f4d48c353fe0a596d4811bc40eee064173a1b6724b1c84fb8f21"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/frgm/releases/download/v0.7.0/frgm_v0.7.0_linux_amd64.tar.gz"
      sha256 "c558c23c9cb5593978eca23cb95e50824220cc8ff0871fa6040c6581c1d30bfc"
    end
  end

  def install
    system './frgm', 'completion', 'bash', '--out', 'frgm.bash'
    system './frgm', 'completion', 'zsh', '--out', 'frgm.zsh'
    bin.install 'frgm'
    bash_completion.install 'frgm.bash' => 'frgm'
    zsh_completion.install 'frgm.zsh' => '_frgm'
  end
end
