# This file was generated by GoReleaser. DO NOT EDIT.
class Frgm < Formula
  desc "frgm is a meta snippet (fragment) manager."
  homepage "https://github.com/k1LoW/frgm"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/frgm/releases/download/v0.4.0/frgm_v0.4.0_darwin_amd64.zip"
    sha256 "00b7348c3bd6b7ce41e5920f5fc7193c7a5195fcfb0ed0f2fd820262f03aae22"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/frgm/releases/download/v0.4.0/frgm_v0.4.0_linux_amd64.tar.gz"
      sha256 "87a64f83386089bef8e5fc12b56a17c23eb7ffb8450d6f5461c98873b3adc921"
    end
  end

  def install
    system './frgm', 'completion', 'bash', '--out', 'frgm.bash'
    system './frgm', 'completion', 'zsh', '--out', 'frgm.zsh'
    bin.install 'frgm'
    bash_completion.install 'frgm.bash' => 'frgm'
    zsh_completion.install 'frgm.zsh' => '_frgm'
  end
end
