# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhGrep < Formula
  desc "Print lines matching a pattern in repositories using GitHub API"
  homepage "https://github.com/k1LoW/gh-grep"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/gh-grep/releases/download/v0.1.0/gh-grep_v0.1.0_darwin_arm64.zip"
      sha256 "3c95e059588cefdd787127f7a621c849ba9ae59144ab711346f7efed8379ca72"

      def install
        bin.install "gh-grep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/gh-grep/releases/download/v0.1.0/gh-grep_v0.1.0_darwin_amd64.zip"
      sha256 "4852cb6b3ab1e99558ce0d5bb98c72facffd422f98c1d04b9da09f041418827e"

      def install
        bin.install "gh-grep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/gh-grep/releases/download/v0.1.0/gh-grep_v0.1.0_linux_amd64.tar.gz"
      sha256 "9c68333a7c3def141062012a9c30aa67b24386797623f69f6b9735122d239b94"

      def install
        bin.install "gh-grep"
      end
    end
  end
end
