# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhGrep < Formula
  desc "Print lines matching a pattern in repositories using GitHub API"
  homepage "https://github.com/k1LoW/gh-grep"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/gh-grep/releases/download/v0.3.0/gh-grep_v0.3.0_darwin_arm64.zip"
      sha256 "598c6da2ad46e43220451e27d5d5d475cfbc57fabc47e42990d0bd9ba6946b16"

      def install
        bin.install "gh-grep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/gh-grep/releases/download/v0.3.0/gh-grep_v0.3.0_darwin_amd64.zip"
      sha256 "6d4ff098e5020d9543236694442e08d06457230891d80691b835a760cddce4b7"

      def install
        bin.install "gh-grep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/gh-grep/releases/download/v0.3.0/gh-grep_v0.3.0_linux_amd64.tar.gz"
      sha256 "61d3ae567b2240dfb9b666a21a6487c17d3410d918348ecc9925aa9508b9f692"

      def install
        bin.install "gh-grep"
      end
    end
  end
end
