# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghdag < Formula
  desc "ghdag is a tiny workflow engine for GitHub issue and pull request."
  homepage "https://github.com/k1LoW/ghdag"
  version "0.2.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/ghdag/releases/download/v0.2.1/ghdag_v0.2.1_darwin_amd64.zip"
    sha256 "ceae6a6d4f8ab2d4f253a62e72453183f66d6559744ca15f092203bf6f1ab7bc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/ghdag/releases/download/v0.2.1/ghdag_v0.2.1_linux_amd64.tar.gz"
    sha256 "ce9a5bcef1583ce2162dab8490d3b3c5a54340b5abf21b5254b83592b8470190"
  end

  def install
    bin.install "ghdag"
  end
end
