# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghdag < Formula
  desc "ghdag is a tiny workflow engine for GitHub issue and pull request."
  homepage "https://github.com/k1LoW/ghdag"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/ghdag/releases/download/v0.1.1/ghdag_v0.1.1_darwin_amd64.zip"
    sha256 "2ae7d4ad3f5cbc126917bdebe3db4af300ee7663a1966cb2a17b861e2abc3632"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/ghdag/releases/download/v0.1.1/ghdag_v0.1.1_linux_amd64.tar.gz"
    sha256 "b0274b8c1b89edaeab82b1a18c2962226af02f6d37466455e735133cb6192755"
  end

  def install
    bin.install "ghdag"
  end
end
