# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghdag < Formula
  desc "ghdag is a tiny workflow engine for GitHub issue and pull request."
  homepage "https://github.com/k1LoW/ghdag"
  version "0.10.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/ghdag/releases/download/v0.10.3/ghdag_v0.10.3_darwin_amd64.zip"
    sha256 "a5cb9ae6f275c9608f9d87eda4aa7ab3ab4a0dbe7ab2954752de2b648da9e264"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/ghdag/releases/download/v0.10.3/ghdag_v0.10.3_linux_amd64.tar.gz"
    sha256 "2f93fd43f8cf5d994c99e2796c74b7658e6f70c21ba8a900a0372d98ce784286"
  end

  def install
    bin.install "ghdag"
  end
end
