# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghput < Formula
  desc "ghput is a CI-friendly tool that puts * on GitHub."
  homepage "https://github.com/k1LoW/ghput"
  version "0.13.0"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/ghput/releases/download/v0.13.0/ghput_v0.13.0_darwin_arm64.zip"
      sha256 "db4016ca8266143b991790216284774f79e48388a95b5ef4c988ccd73acc5af5"

      def install
        system './ghput', 'completion', 'bash', '--out', 'ghput.bash'
        system './ghput', 'completion', 'zsh', '--out', 'ghput.zsh'
        bin.install 'ghput'
        bash_completion.install 'ghput.bash' => 'ghput'
        zsh_completion.install 'ghput.zsh' => '_ghput'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ghput/releases/download/v0.13.0/ghput_v0.13.0_darwin_amd64.zip"
      sha256 "d2e90e4d15e33d4e10c8c7da3d03e2bb8ac85be23eeb81c6c7059f4156f755b9"

      def install
        system './ghput', 'completion', 'bash', '--out', 'ghput.bash'
        system './ghput', 'completion', 'zsh', '--out', 'ghput.zsh'
        bin.install 'ghput'
        bash_completion.install 'ghput.bash' => 'ghput'
        zsh_completion.install 'ghput.zsh' => '_ghput'
      end
    end
  end
end
