# This file was generated by GoReleaser. DO NOT EDIT.
class Ghput < Formula
  desc "ghput is a CI-Friendly tool for put comment on GitHub."
  homepage "https://github.com/k1LoW/ghput"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/ghput/releases/download/v0.2.1/ghput_v0.2.1_darwin_amd64.zip"
    sha256 "68b6e1ade441d96b2fefef2ffd7d29902f5ad7b9e9ff88e62dd432faa51bef77"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ghput/releases/download/v0.2.1/ghput_v0.2.1_linux_amd64.tar.gz"
      sha256 "9e37486646e19a300b2959cb663674c77dacbaf92653e0dddcb43d07a93a2e11"
    end
  end

  def install
    system './ghput', 'completion', 'bash', '--out', 'ghput.bash'
    system './ghput', 'completion', 'zsh', '--out', 'ghput.zsh'
    bin.install 'ghput'
    bash_completion.install 'ghput.bash' => 'ghput'
    zsh_completion.install 'ghput.zsh' => '_ghput'
  end
end
