# This file was generated by GoReleaser. DO NOT EDIT.
class Harvest < Formula
  desc "Portable log aggregation tool for middle-scale system operation/observation."
  homepage "https://github.com/k1LoW/harvest"
  version "0.15.2"

  if OS.mac?
    url "https://github.com/k1LoW/harvest/releases/download/v0.15.2/harvest_v0.15.2_darwin_amd64.zip"
    sha256 "3219fd3ab238697539358f8718baaceb229e6363995b4c4f0ea783f7ac62848a"
  elsif OS.linux?
    url "https://github.com/k1LoW/harvest/releases/download/v0.15.2/harvest_v0.15.2_linux_amd64.tar.gz"
    sha256 "4daff8499f1dfc1bbc417542b17fc0ec78d1bfe2a02626d65d90a1a4ecc52915"
  end

  def install
    bin.install 'hrv'
  end
end
