# This file was generated by GoReleaser. DO NOT EDIT.
class Lrep < Formula
  desc "line regular expression parser"
  homepage "https://github.com/k1LoW/lrep"
  version "0.3.0"

  if OS.mac?
    url "https://github.com/k1LoW/lrep/releases/download/v0.3.0/lrep_v0.3.0_darwin_amd64.zip"
    sha256 "1fbb17602ca15acf1e1c6f55485c2dfb5e50a952460b4aab9b189ddcd2319bd5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/lrep/releases/download/v0.3.0/lrep_v0.3.0_linux_amd64.tar.gz"
      sha256 "b188948379ad8094c6acbb9c4cc8d4fe52a8b78892c4f5d211af6c73f7ca8697"
    end
  end

  def install
    system './lrep', 'completion', 'bash', '--out', 'lrep.bash'
    system './lrep', 'completion', 'zsh', '--out', 'lrep.zsh'
    bin.install 'lrep'
    bash_completion.install 'lrep.bash' => 'lrep'
    zsh_completion.install 'lrep.zsh' => '_lrep'
  end
end
