# This file was generated by GoReleaser. DO NOT EDIT.
class Lrep < Formula
  desc "line regular expression parser"
  homepage "https://github.com/k1LoW/lrep"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/lrep/releases/download/v0.1.0/lrep_v0.1.0_darwin_amd64.zip"
    sha256 "b356989f46f4f27e436430cce8edc896c4a3b33cfebe1cf3547d647193e94a75"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/lrep/releases/download/v0.1.0/lrep_v0.1.0_linux_amd64.tar.gz"
      sha256 "b274d7bb53a1b51b2b4a91d53a46a05ad9b338c5b448569cbea670ac2994f405"
    end
  end

  def install
    system './lrep', 'completion', 'bash', '--out', 'lrep.bash'
    system './lrep', 'completion', 'zsh', '--out', 'lrep.zsh'
    bin.install 'lrep'
    bash_completion.install 'lrep.bash' => 'lrep'
    zsh_completion.install 'lrep.zsh' => '_lrep'
  end
end
