# This file was generated by GoReleaser. DO NOT EDIT.
class Lrep < Formula
  desc "line regular expression parser"
  homepage "https://github.com/k1LoW/lrep"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/lrep/releases/download/v0.2.0/lrep_v0.2.0_darwin_amd64.zip"
    sha256 "6fbc9e4970cc93f8c1b1e5ce65363c18bbbd26841df83e0749fab9b8c1777a2d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/lrep/releases/download/v0.2.0/lrep_v0.2.0_linux_amd64.tar.gz"
      sha256 "86c30e94fdada24e0249c4b650a4e2d4974561f00e73cdfdba8c2476e3cc659c"
    end
  end

  def install
    system './lrep', 'completion', 'bash', '--out', 'lrep.bash'
    system './lrep', 'completion', 'zsh', '--out', 'lrep.zsh'
    bin.install 'lrep'
    bash_completion.install 'lrep.bash' => 'lrep'
    zsh_completion.install 'lrep.zsh' => '_lrep'
  end
end
