# This file was generated by GoReleaser. DO NOT EDIT.
class Ndiag < Formula
  desc "ndiag is a high-level architecture diagramming/documentation tool."
  homepage "https://github.com/k1LoW/ndiag"
  version "0.12.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/ndiag/releases/download/v0.12.0/ndiag_v0.12.0_darwin_amd64.zip"
    sha256 "605e7a038d7493d622fdc503587c46aa6553da31ff053d1b1b7286228b5d94e4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ndiag/releases/download/v0.12.0/ndiag_v0.12.0_linux_amd64.tar.gz"
      sha256 "5fc7f68784d41dce82d96152b9227038eae7ac76316e5e9e14807aede291f91a"
    end
  end

  def install
    system './ndiag', 'completion', 'bash', '--out', 'ndiag.bash'
    system './ndiag', 'completion', 'zsh', '--out', 'ndiag.zsh'
    bin.install 'ndiag'
    bash_completion.install 'ndiag.bash' => 'ndiag'
    zsh_completion.install 'ndiag.zsh' => '_ndiag'
  end
end
