# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oshka < Formula
  desc "oshka is a tool for extracting nested CI/CD supply chains and executing commands."
  homepage "https://github.com/k1LoW/oshka"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/oshka/releases/download/v0.2.0/oshka_v0.2.0_darwin_amd64.zip"
      sha256 "4f7454e176d6bfd73d746d8297cb66da6b04f72c990b258b34b6088cc5334260"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/oshka/releases/download/v0.2.0/oshka_v0.2.0_linux_amd64.tar.gz"
      sha256 "902f2a53f96ffcb4144c1a452ca632945bdcb56ad7944527d03f46b2f9323d11"
    end
  end

  def install
    bin.install "oshka"
  end
end
