# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oshka < Formula
  desc "oshka is a tool for extracting nested CI/CD supply chains and executing commands."
  homepage "https://github.com/k1LoW/oshka"
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/oshka/releases/download/v0.3.0/oshka_v0.3.0_darwin_amd64.zip"
      sha256 "e51dd0800262ebff192c70d3d0327f2943c458e314cc9a8f8e3ddc0528faf246"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/oshka/releases/download/v0.3.0/oshka_v0.3.0_linux_amd64.tar.gz"
      sha256 "8edb240bf7a1757f704b3b96ccd110316eb03f029910738ee19864276c633e48"
    end
  end

  def install
    bin.install "oshka"
  end
end
