# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrRevert < Formula
  desc "pr-revert is a tool for reverting pull requests."
  homepage "https://github.com/k1LoW/pr-revert"
  version "0.2.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/pr-revert/releases/download/v0.2.2/pr-revert_v0.2.2_darwin_amd64.zip"
      sha256 "a7caa208cc4702d1667b658bfcfa6bf6d64098da9a5a6125fc85b81463a8a215"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/pr-revert/releases/download/v0.2.2/pr-revert_v0.2.2_linux_amd64.tar.gz"
      sha256 "80155114156d934dfad66a35e4368ced601faa595754119bd3e6ac62dd181f6d"
    end
  end

  def install
    bin.install "pr-revert"
  end
end
