# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrRevert < Formula
  desc "pr-revert is a tool for reverting pull requests."
  homepage "https://github.com/k1LoW/pr-revert"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/pr-revert/releases/download/v0.4.2/pr-revert_v0.4.2_darwin_arm64.zip"
      sha256 "cac401e6a6ec4485a6476b44b2d3226ed12e60f3bd9a5a2502e740256474e00e"

      def install
        bin.install "pr-revert"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/pr-revert/releases/download/v0.4.2/pr-revert_v0.4.2_darwin_amd64.zip"
      sha256 "3228baf50c0413288c428c77916200e0dbd350dff874094af44f671eabaa15e3"

      def install
        bin.install "pr-revert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/pr-revert/releases/download/v0.4.2/pr-revert_v0.4.2_linux_amd64.tar.gz"
      sha256 "1079f3ea9cb59a479421a9ffee23eb1b96a54fa45fe2724ad6f441a92ce168ed"

      def install
        bin.install "pr-revert"
      end
    end
  end
end
