# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repin < Formula
  desc "repin is a tool to replace strings between keyword pair."
  homepage "https://github.com/k1LoW/repin"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/repin/releases/download/v0.4.1/repin_v0.4.1_darwin_arm64.zip"
      sha256 "4c543a79f9a4de7cd90afb444562f6df99bcd1d31022b0e3489fd7b5ff20dd1a"

      def install
        bin.install 'repin'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/repin/releases/download/v0.4.1/repin_v0.4.1_darwin_amd64.zip"
      sha256 "c0fc77df1c1bccdd1cbba6aaa99a173f521908dc97d415ee0354f240ef67e310"

      def install
        bin.install 'repin'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/repin/releases/download/v0.4.1/repin_v0.4.1_linux_amd64.tar.gz"
      sha256 "836cbd9cc574b71a7fe1c3cec8963333e9c22b6dd80c8b3654bcb3d19edbe2d4"

      def install
        bin.install 'repin'
      end
    end
  end
end
