# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repin < Formula
  desc "repin is a tool to replace strings between keyword pair."
  homepage "https://github.com/k1LoW/repin"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/repin/releases/download/v0.3.0/repin_v0.3.0_darwin_arm64.zip"
      sha256 "5d4ae9461dc13c4d44836f65a54af24d6d00281426e6113ca0dcd162a1c08472"

      def install
        bin.install 'repin'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/repin/releases/download/v0.3.0/repin_v0.3.0_darwin_amd64.zip"
      sha256 "9ce8c6020b1fcec95e7120dc5169eb07578e1a677bbd164331eac15c63510e6b"

      def install
        bin.install 'repin'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/repin/releases/download/v0.3.0/repin_v0.3.0_linux_amd64.tar.gz"
      sha256 "f159bff49f0f1700c4301fdc3251879a66dea9d19b420ba630105af3c912d2ee"

      def install
        bin.install 'repin'
      end
    end
  end
end
