# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runbk < Formula
  desc "runbk is a tool for running operations following a scenario."
  homepage "https://github.com/k1LoW/runbk"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/runbk/releases/download/v0.0.1/runbk_v0.0.1_darwin_arm64.zip"
      sha256 "79e73e994011965858eff75f7ec1d898015465da9cd1c5d93f9842c6f9c4f0ca"

      def install
        bin.install 'runbk'
        output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'bash')
        (bash_completion/'runbk').write output
        output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'zsh')
        (zsh_completion/'_runbk').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/runbk/releases/download/v0.0.1/runbk_v0.0.1_darwin_amd64.zip"
      sha256 "44199f3760e456f004672fae1979d05fb8297d11b267d59f934aed2f253965b9"

      def install
        bin.install 'runbk'
        output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'bash')
        (bash_completion/'runbk').write output
        output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'zsh')
        (zsh_completion/'_runbk').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/runbk/releases/download/v0.0.1/runbk_v0.0.1_linux_amd64.tar.gz"
      sha256 "dcb26b328b42b44239b7f79cce89c17f923d852af95b989f6a134832109524be"

      def install
        bin.install 'runbk'
        output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'bash')
        (bash_completion/'runbk').write output
        output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'zsh')
        (zsh_completion/'_runbk').write output
      end
    end
  end
end
