# This file was generated by GoReleaser. DO NOT EDIT.
class Slackln < Formula
  desc "Println(Slack)."
  homepage "https://github.com/k1LoW/slackln"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/slackln/releases/download/v0.2.0/slackln_v0.2.0_darwin_amd64.zip"
    sha256 "a49f53fbf2d5872071d8dfedc0020d44454f06308e8b247e3add2e675753e53c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/slackln/releases/download/v0.2.0/slackln_v0.2.0_linux_amd64.tar.gz"
      sha256 "1a6332cd7a60d6493445683103b6ed512e6dfd09f9fd48b639bdbc89c24bc03d"
    end
  end

  def install
    system './slackln', 'completion', 'bash', '--out', 'slackln.bash'
    system './slackln', 'completion', 'zsh', '--out', 'slackln.zsh'
    bin.install 'slackln'
    bash_completion.install 'slackln.bash' => 'slackln'
    zsh_completion.install 'slackln.zsh' => '_slackln'
  end
end
