# This file was generated by GoReleaser. DO NOT EDIT.
class Slackln < Formula
  desc "Println(Slack)."
  homepage "https://github.com/k1LoW/slackln"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/slackln/releases/download/v0.1.0/slackln_v0.1.0_darwin_amd64.zip"
    sha256 "c6b7969423db4e242a7731e5cede00948cc19f56c331a4fd93397ff6d2130c7e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/slackln/releases/download/v0.1.0/slackln_v0.1.0_linux_amd64.tar.gz"
      sha256 "ea637ad039b3be0a2bcae690787af36a5b1fe7db3cd42d6b8f9232bfe42088ef"
    end
  end

  def install
    bin.install 'slackln'
  end
end
