class SqlcGoOneOrFail < Formula
  desc 'Modify the Go code generated by sqlc to fail if more than one record is retrieved in the `:one` command.'
  version '0.3.1'
  homepage 'https://github.com/k1LoW/sqlc-go-one-or-fail'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.3.1/sqlc-go-one-or-fail_v0.3.1_darwin_arm64.zip'
      sha256 '2c31f591221541a01b0ea4840012e3e0b4f33bcbccb2a73375bb9896f514e937'
    end
    if Hardware::CPU.intel?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.3.1/sqlc-go-one-or-fail_v0.3.1_darwin_amd64.zip'
      sha256 'bb4b5260e8022c2f320a545fd516be16456e6167ce09f4d7566fb4e2855408d9'
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.3.1/sqlc-go-one-or-fail_v0.3.1_linux_arm64.tar.gz'
      sha256 '165f1459ba89308fba6509ff5005efa61dc8a20b328d501c75fb033adaae4655'
    end
    if Hardware::CPU.intel?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.3.1/sqlc-go-one-or-fail_v0.3.1_linux_amd64.tar.gz'
      sha256 'f17112f3db0c8abc990035246483b9a1abf5755dc6a6e08336f0ea0110cc2769'
    end
  end

  head do
    url 'https://github.com/k1LoW/sqlc-go-one-or-fail.git'
    depends_on 'go' => :build
  end

  def install
    system 'make', 'build' if build.head?
    bin.install 'sqlc-go-one-or-fail'
    generate_completions_from_executable(bin/'sqlc-go-one-or-fail', 'completion')
  end
end
