class SqlcGoOneOrFail < Formula
  desc 'Modify the Go code generated by sqlc to fail if more than one record is retrieved in the `:one` command.'
  version '0.1.0'
  homepage 'https://github.com/k1LoW/sqlc-go-one-or-fail'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.1.0/sqlc-go-one-or-fail_v0.1.0_darwin_arm64.zip'
      sha256 '16f37260c525dc335c47875c445827dc749eb7502bab832f9d4a8a7c5d9a35b5'
    end
    if Hardware::CPU.intel?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.1.0/sqlc-go-one-or-fail_v0.1.0_darwin_amd64.zip'
      sha256 'b19d61660f7b76c6e4135d7e072ff02f449ccf02dfc820c94d4bd16c24a25846'
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.1.0/sqlc-go-one-or-fail_v0.1.0_linux_arm64.tar.gz'
      sha256 '04ac33d4730eef9b172014f4d7bf080f85ab2b3dddc6ca42ec0b53f49f0fffbb'
    end
    if Hardware::CPU.intel?
      url 'https://github.com/k1LoW/sqlc-go-one-or-fail/releases/download/v0.1.0/sqlc-go-one-or-fail_v0.1.0_linux_amd64.tar.gz'
      sha256 '7ffa84ad8e2f9096f3ad4f61a358e62882aea6e90e86ab6b24ab8dbb78060640'
    end
  end

  head do
    url 'https://github.com/k1LoW/sqlc-go-one-or-fail.git'
    depends_on 'go' => :build
  end

  def install
    system 'make', 'build' if build.head?
    bin.install 'sqlc-go-one-or-fail'
    generate_completions_from_executable(bin/'sqlc-go-one-or-fail', 'completion')
  end
end
