# This file was generated by GoReleaser. DO NOT EDIT.
class TblsCacoo < Formula
  desc "tbls-cacoo is an external subcommand of tbls for Cacoo."
  homepage "https://github.com/k1LoW/tbls-cacoo"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls-cacoo/releases/download/v0.2.0/tbls-cacoo_v0.2.0_darwin_amd64.zip"
    sha256 "a330037babef578e1211dbc027e3fe5a6bc5ff52527eb51bb5d0558b3601f67f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-cacoo/releases/download/v0.2.0/tbls-cacoo_v0.2.0_linux_amd64.tar.gz"
      sha256 "b062386fb0f1c5bbad0cd0bed73a373d4c38e5230fe67a0b3b6d0124209bef0d"
    end
  end
  
  depends_on "tbls"

  def install
    system './tbls-cacoo', 'completion', 'bash', '--out', 'tbls-cacoo.bash'
    system './tbls-cacoo', 'completion', 'zsh', '--out', 'tbls-cacoo.zsh'
    bin.install 'tbls-cacoo'
    bash_completion.install 'tbls-cacoo.bash' => 'tbls-cacoo'
    zsh_completion.install 'tbls-cacoo.zsh' => '_tbls-cacoo'
  end
end
