# This file was generated by GoReleaser. DO NOT EDIT.
class TblsCacoo < Formula
  desc "tbls-cacoo is an external subcommand of tbls for Cacoo."
  homepage "https://github.com/k1LoW/tbls-cacoo"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls-cacoo/releases/download/v0.1.0/tbls-cacoo_v0.1.0_darwin_amd64.zip"
    sha256 "94ee3b8b4ef1b4aef73f9e895b97b3afddfb43ef32c1cffb8b4ec2acbb8c9a66"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-cacoo/releases/download/v0.1.0/tbls-cacoo_v0.1.0_linux_amd64.tar.gz"
      sha256 "a98808792acc2e48ffb89b983e8ddf5cf72a3cd6d670c9c3d36ab3707631f8b1"
    end
  end
  
  depends_on "tbls"

  def install
    system './tbls-cacoo', 'completion', 'bash', '--out', 'tbls-cacoo.bash'
    system './tbls-cacoo', 'completion', 'zsh', '--out', 'tbls-cacoo.zsh'
    bin.install 'tbls-cacoo'
    bash_completion.install 'tbls-cacoo.bash' => 'tbls-cacoo'
    zsh_completion.install 'tbls-cacoo.zsh' => '_tbls-cacoo'
  end
end
