# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbls < Formula
  desc "tbls is a CI-Friendly tool for document a database, written in Go."
  homepage "https://github.com/k1LoW/tbls"
  version "1.49.7"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/tbls/releases/download/v1.49.7/tbls_v1.49.7_darwin_amd64.zip"
    sha256 "020d7f1ad90c0cb17da3eabf097ee81f6d1553e4e4a42103a421a71c099440f5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/k1LoW/tbls/releases/download/v1.49.7/tbls_v1.49.7_linux_amd64.tar.gz"
    sha256 "d788820fee5b165a9d163853eb28727317bd7f3766d508a7edf6ffe14c91278f"
  end

  def install
    system './tbls', 'completion', 'bash', '--out', 'tbls.bash'
    system './tbls', 'completion', 'zsh', '--out', 'tbls.zsh'
    bin.install 'tbls'
    bash_completion.install 'tbls.bash' => 'tbls'
    zsh_completion.install 'tbls.zsh' => '_tbls'
  end
end
