# This file was generated by GoReleaser. DO NOT EDIT.
class TblsMeta < Formula
  desc "tbls-meta is an external subcommand of tbls for applying metadata managed by tbls to the datasource."
  homepage "https://github.com/k1LoW/tbls-meta"
  version "0.2.2"

  if OS.mac?
    url "https://github.com/k1LoW/tbls-meta/releases/download/v0.2.2/tbls-meta_v0.2.2_darwin_amd64.zip"
    sha256 "07cc0e3f0ea998243f1646ea44f4ef8dfeff80de8a3c0f72361ea79365ab39fd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-meta/releases/download/v0.2.2/tbls-meta_v0.2.2_linux_amd64.tar.gz"
      sha256 "ffc381b8c1a89309ab4be0b0883064ba864cd931a93942967b98f4899ef121cf"
    end
  end

  depends_on "tbls"

  def install
    system './tbls-meta', 'completion', 'bash', '--out', 'tbls-meta.bash'
    system './tbls-meta', 'completion', 'zsh', '--out', 'tbls-meta.zsh'
    bin.install 'tbls-meta'
    bash_completion.install 'tbls-meta.bash' => 'tbls-meta'
    zsh_completion.install 'tbls-meta.zsh' => '_tbls-meta'
  end
end
