# This file was generated by GoReleaser. DO NOT EDIT.
class TblsPush < Formula
  desc "tbls-push is an external subcommand of tbls for pushing schema data (schema.json) to target GitHub repository."
  homepage "https://github.com/k1LoW/tbls-push"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls-push/releases/download/v0.1.0/tbls-push_v0.1.0_darwin_amd64.zip"
    sha256 "ec637094e008d52b818732c42bd4ee822cb6adeefe8ef53091399dc927a7c4c2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-push/releases/download/v0.1.0/tbls-push_v0.1.0_linux_amd64.tar.gz"
      sha256 "9cd50f6ceb5e45c64c3c9d9181c184bc610dc5d75b6c9b769b1ca4c60c0bb566"
    end
  end
  
  depends_on "tbls"

  def install
    system './tbls-push', 'completion', 'bash', '--out', 'tbls-push.bash'
    system './tbls-push', 'completion', 'zsh', '--out', 'tbls-push.zsh'
    bin.install 'tbls-push'
    bash_completion.install 'tbls-push.bash' => 'tbls-push'
    zsh_completion.install 'tbls-push.zsh' => '_tbls-push'
  end
end
