# This file was generated by GoReleaser. DO NOT EDIT.
class TblsBuild < Formula
  desc "tbls-build is an external subcommand of tbls for customizing config file of tbls using other tbls.yml or schema.json."
  homepage "https://github.com/k1LoW/tbls-build"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls-build/releases/download/v0.2.1/tbls-build_v0.2.1_darwin_amd64.zip"
    sha256 "d7ed77af5113362eb4556b944a1cc6cebfb2ff0bc99c4672f1458c08a71c93ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-build/releases/download/v0.2.1/tbls-build_v0.2.1_linux_amd64.tar.gz"
      sha256 "e834ef6ab7d2cce8546cb1cee58b612d4f38be851e39848e48e50ec9d297d2bf"
    end
  end
  
  depends_on "tbls"

  def install
    system './tbls-build', 'completion', 'bash', '--out', 'tbls-build.bash'
    system './tbls-build', 'completion', 'zsh', '--out', 'tbls-build.zsh'
    bin.install 'tbls-build'
    bash_completion.install 'tbls-build.bash' => 'tbls-build'
    zsh_completion.install 'tbls-build.zsh' => '_tbls-build'
  end
end
