# This file was generated by GoReleaser. DO NOT EDIT.
class TblsBuild < Formula
  desc "tbls-build is an external subcommand of tbls for customizing config file of tbls using other tbls.yml or schema.json."
  homepage "https://github.com/k1LoW/tbls-build"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls-build/releases/download/v0.2.2/tbls-build_v0.2.2_darwin_amd64.zip"
    sha256 "3e7630e85f10ab8392374accf96c3282babaf92c68ab156f5ed915483319d843"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-build/releases/download/v0.2.2/tbls-build_v0.2.2_linux_amd64.tar.gz"
      sha256 "42237b8220cfa01fa5d5aa52a68d6c8a6bd981870c2971070161b61227dd002d"
    end
  end
  
  depends_on "tbls"

  def install
    system './tbls-build', 'completion', 'bash', '--out', 'tbls-build.bash'
    system './tbls-build', 'completion', 'zsh', '--out', 'tbls-build.zsh'
    bin.install 'tbls-build'
    bash_completion.install 'tbls-build.bash' => 'tbls-build'
    zsh_completion.install 'tbls-build.zsh' => '_tbls-build'
  end
end
