# This file was generated by GoReleaser. DO NOT EDIT.
class Tbls < Formula
  desc "tbls is a CI-Friendly tool for document a database, written in Go."
  homepage "https://github.com/k1LoW/tbls"
  version "1.38.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls/releases/download/v1.38.1/tbls_v1.38.1_darwin_amd64.zip"
    sha256 "e605d849a390ca7724ad8ef851ed2f793c1b31cb9c4f9f87b330d8a44410a10f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls/releases/download/v1.38.1/tbls_v1.38.1_linux_amd64.tar.gz"
      sha256 "887ee653363647ad43e76dee3f31bbfe28eba3bc9f36c46034931e2ff21ffaa1"
    end
  end

  def install
    system './tbls', 'completion', 'bash', '--out', 'tbls.bash'
    system './tbls', 'completion', 'zsh', '--out', 'tbls.zsh'
    bin.install 'tbls'
    bash_completion.install 'tbls.bash' => 'tbls'
    zsh_completion.install 'tbls.zsh' => '_tbls'
  end
end
