# This file was generated by GoReleaser. DO NOT EDIT.
class TblsMeta < Formula
  desc "tbls-meta is an external subcommand of tbls for applying metadata managed by tbls to the datasource."
  homepage "https://github.com/k1LoW/tbls-meta"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/tbls-meta/releases/download/v0.2.0/tbls-meta_v0.2.0_darwin_amd64.zip"
    sha256 "5c65c7e5db45bc31c226a6030ff791281cd4e1857158e5b712b4167da982cb06"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/tbls-meta/releases/download/v0.2.0/tbls-meta_v0.2.0_linux_amd64.tar.gz"
      sha256 "962ff433aea20d18edc17161b330098fc94ede759b620bdd148e21658b80768a"
    end
  end
  
  depends_on "tbls"

  def install
    system './tbls-meta', 'completion', 'bash', '--out', 'tbls-meta.bash'
    system './tbls-meta', 'completion', 'zsh', '--out', 'tbls-meta.zsh'
    bin.install 'tbls-meta'
    bash_completion.install 'tbls-meta.bash' => 'tbls-meta'
    zsh_completion.install 'tbls-meta.zsh' => '_tbls-meta'
  end
end
