# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrivyDbTo < Formula
  desc "trivy-db-to is a tool for migrating/converting vulnerability information from Trivy DB to other datasource."
  homepage "https://github.com/k1LoW/trivy-db-to"
  version "2.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/trivy-db-to/releases/download/v2.0.5/trivy-db-to_v2.0.5_darwin_arm64.zip"
      sha256 "1d5133e140101a71bc386ef4ba85f77ff78e8f88336759f8679998be934f55f6"

      def install
        bin.install "trivy-db-to"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/trivy-db-to/releases/download/v2.0.5/trivy-db-to_v2.0.5_darwin_amd64.zip"
      sha256 "3f455adcfa641cb11d76b30679f0d3cbe68cf95ebf77009435b2dbaeb022256f"

      def install
        bin.install "trivy-db-to"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/trivy-db-to/releases/download/v2.0.5/trivy-db-to_v2.0.5_linux_amd64.tar.gz"
      sha256 "802e3c5d001db36a93158770a7b9c4e334842d05bdd8f455b5aa05dfe9c0594e"

      def install
        bin.install "trivy-db-to"
      end
    end
  end
end
