# This file was generated by GoReleaser. DO NOT EDIT.
class Tsplt < Formula
  desc "plot time series data."
  homepage "https://github.com/k1LoW/tsplt"
  version "0.2.1"

  if OS.mac?
    url "https://github.com/k1LoW/tsplt/releases/download/v0.2.1/tsplt_v0.2.1_darwin_amd64.zip"
    sha256 "85d5af0321b7818da1b85583d68e24a46632847251c3c4cc718aefc4499a2888"
  elsif OS.linux?
    url "https://github.com/k1LoW/tsplt/releases/download/v0.2.1/tsplt_v0.2.1_linux_amd64.tar.gz"
    sha256 "fafe745b11417d99cf058eef0c32d7caa33383d68a627eb2b0dffc91a2a03780"
  end

  def install
    bin.install 'tsplt'
  end
end
