# This file was generated by GoReleaser. DO NOT EDIT.
class Tsplt < Formula
  desc "plot time series data."
  homepage "https://github.com/k1LoW/tsplt"
  version "0.2.0"

  if OS.mac?
    url "https://github.com/k1LoW/tsplt/releases/download/v0.2.0/tsplt_v0.2.0_darwin_amd64.zip"
    sha256 "81d8682516cb30d1590ad5748af98dd48fb98c2aaf2f29126da448fa76c771b7"
  elsif OS.linux?
    url "https://github.com/k1LoW/tsplt/releases/download/v0.2.0/tsplt_v0.2.0_linux_amd64.tar.gz"
    sha256 "405f6271b94ed07803df43f8018758d6b561624e9338663443bf8de2c0eca12d"
  end

  def install
    bin.install 'tsplt'
  end
end
