# This file was generated by GoReleaser. DO NOT EDIT.
class Tsplt < Formula
  desc "plot time series data."
  homepage "https://github.com/k1LoW/tsplt"
  version "0.1.0"

  if OS.mac?
    url "https://github.com/k1LoW/tsplt/releases/download/v0.1.0/tsplt_v0.1.0_darwin_amd64.zip"
    sha256 "d0757ebf803fc0117a481f72680b7f6991dbc0b4d166e0d7f4f53ff88c597280"
  elsif OS.linux?
    url "https://github.com/k1LoW/tsplt/releases/download/v0.1.0/tsplt_v0.1.0_linux_amd64.tar.gz"
    sha256 "d50fe41eaa48de01c676b79db75fc4d9b3ac1f4b6720b00a70a0a9179a40e728"
  end

  def install
    bin.install 'tsplt'
  end
end
