# This file was generated by GoReleaser. DO NOT EDIT.
class Ttff < Formula
  desc "ttff is a tool for TrueType Font Files"
  homepage "https://github.com/k1LoW/ttff"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/k1LoW/ttff/releases/download/v0.1.0/ttff_v0.1.0_darwin_amd64.zip"
    sha256 "ca7e73678f29a118dba0fc9d83f9bc6fdfb29b372969b6cbfbd4232a2386e79a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/ttff/releases/download/v0.1.0/ttff_v0.1.0_linux_amd64.tar.gz"
      sha256 "aa46c1e623713a973efce2e9f2f5f12edcae6d0e8ce0590b740435b3f1276bb9"
    end
  end

  def install
    bin.install "ttff"
  end
end
